# Generated by Django 4.1.5 on 2023-07-01 11:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('images3D', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('theCollectibleDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('aboutDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('blockInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('isPreorder', models.BooleanField()),
                ('releaseDate', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('quantityAvailable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_review_pfp)),
                ('reviewImage', models.ImageField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_review_image)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
