# Generated by Django 4.1.5 on 2023-07-02 07:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='displayImage',
            field=models.ImageField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_item_display),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_item_all_images),
        ),
        migrations.AlterField(
            model_name='item',
            name='images3D',
            field=models.ImageField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_item_3d),
        ),
    ]
