# Generated by Django 4.1.5 on 2023-07-02 07:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_displayimage_alter_item_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images3D',
            field=models.FileField(default='pfps/default_pfp.jpg', upload_to=api.models.upload_path_item_3d),
        ),
    ]
