# Generated by Django 4.1.5 on 2023-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_item_images_remove_item_images3d_imagelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isPreorder',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
