# Generated by Django 4.1.5 on 2023-07-03 21:39

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_ispreorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='displayImage',
        ),
        migrations.AlterField(
            model_name='image3d',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path_item_3d),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path_item_all_images),
        ),
        migrations.CreateModel(
            name='DisplayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_path_item_display)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
    ]
