# Generated by Django 4.1.5 on 2023-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_item_displayimage_alter_image3d_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayimage',
            name='a',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='image3d',
            name='a',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='a',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
