# Generated by Django 4.1.5 on 2023-07-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_item_aboutdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, default='South Park', max_length=255, null=True),
        ),
    ]
