# Generated by Django 4.1.5 on 2023-07-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
    ]
