# Generated by Django 4.1.5 on 2023-07-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
