# Generated by Django 4.1.5 on 2023-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
