# Generated by Django 4.1.5 on 2023-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_item_author_item_main_text_item_quote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main_text',
            new_name='mainText',
        ),
    ]
