# Generated by Django 4.1.5 on 2023-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_item_maintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='item',
            name='day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='hour',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='madeBy',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='month',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
