# Generated by Django 4.1.5 on 2023-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_item_day_alter_item_hour_alter_item_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isPreorder',
        ),
        migrations.AddField(
            model_name='item',
            name='orderType',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
