# Generated by Django 4.1.5 on 2023-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_item_ispreorder_item_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='censor',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
