# Generated by Django 4.1.5 on 2023-08-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_item_censor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blurred',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
