# Generated by Django 4.1.5 on 2023-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_blurimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='day1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hour1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='month1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
