# Generated by Django 4.1.5 on 2023-08-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_item_day1_item_hour1_item_month1_item_year1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='day',
            new_name='day0',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='hour',
            new_name='hour0',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='month',
            new_name='month0',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='year',
            new_name='year0',
        ),
    ]
