# Generated by Django 4.1.5 on 2023-08-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_day_item_day0_rename_hour_item_hour0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='month0',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='day0',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='year0',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='hour0',
            new_name='year',
        ),
    ]
